"""add travelgroup relationship to trips

Revision ID: 04f89056107d
Revises: 95e3300358fc
Create Date: 2025-09-23 18:15:32.967659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f89056107d'
down_revision = '95e3300358fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travelgroup_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_trips_travelgroup_id_travelgroups'), 'travelgroups', ['travelgroup_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trips_travelgroup_id_travelgroups'), type_='foreignkey')
        batch_op.drop_column('travelgroup_id')

    # ### end Alembic commands ###
