"""Adding relationship between Trip and TravelGroup Model

Revision ID: 7742183c1ca0
Revises: b915352e4348
Create Date: 2025-09-24 11:14:32.490336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7742183c1ca0'
down_revision = 'b915352e4348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelgroups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_travelgroups_trip_id_trips'), 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelgroups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_travelgroups_trip_id_trips'), type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###
