"""Returning to initial working migration

Revision ID: b915352e4348
Revises: 04f89056107d
Create Date: 2025-09-23 18:46:06.648628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b915352e4348'
down_revision = '04f89056107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trips_travelgroup_id_travelgroups', type_='foreignkey')
        batch_op.drop_column('travelgroup_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travelgroup_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_trips_travelgroup_id_travelgroups', 'travelgroups', ['travelgroup_id'], ['id'])

    # ### end Alembic commands ###
